import logging
import uuid
from typing import Optional
from github import Github, Auth
from ..models.db_config import get_weaviate_settings

logger = logging.getLogger(__name__)

class PRManager:
    """
    Manages GitHub Pull Requests for VectorWave Healer.
    Requires 'PyGithub' installed.
    """
    def __init__(self):
        self.settings = get_weaviate_settings()
        if not self.settings.GITHUB_TOKEN or not self.settings.GITHUB_REPO_NAME:
            logger.warning("⚠️ GITHUB_TOKEN or GITHUB_REPO_NAME not set. Auto-PR disabled.")
            self.client = None
            self.repo = None
        else:
            try:
                auth = Auth.Token(self.settings.GITHUB_TOKEN)
                self.client = Github(auth=auth)
                self.repo = self.client.get_repo(self.settings.GITHUB_REPO_NAME)
                logger.info(f"Connected to GitHub Repo: {self.settings.GITHUB_REPO_NAME}")
            except Exception as e:
                logger.error(f"Failed to connect to GitHub: {e}")
                self.client = None

    def create_fix_pr(self, file_path: str, function_name: str, new_file_content: str, diagnosis: str) -> str:
        """
        Creates a new branch with the fixed code and opens a Pull Request.
        """
        if not self.client or not self.repo:
            return "❌ GitHub settings are missing or connection failed."

        base_branch = self.settings.GITHUB_BASE_BRANCH
        new_branch_name = f"fix/healer-{function_name.lower()}-{str(uuid.uuid4())[:8]}"

        try:
            # 1. Get SHA of the base branch
            sb = self.repo.get_branch(base_branch)
            base_sha = sb.commit.sha

            # 2. Create new branch (Ref)
            self.repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=base_sha)
            logger.info(f"🌿 Created branch: {new_branch_name}")

            # 3. Get original file SHA to update it
            try:
                contents = self.repo.get_contents(file_path, ref=new_branch_name)
            except Exception:
                return f"❌ File not found in repo: {file_path}"

            # 4. Commit changes
            self.repo.update_file(
                path=file_path,
                message=f"🚑 [Healer] Fix bug in {function_name}",
                content=new_file_content,
                sha=contents.sha,
                branch=new_branch_name
            )
            logger.info(f"💾 Committed fix to {file_path}")

            # 5. Create Pull Request
            pr_title = f"[Healer] Fix detected bug in `{function_name}`"
            pr_body = f"""
## 🚑 VectorWave Auto-Healer Report
**Target Function:** `{function_name}`
**Diagnosis:** {diagnosis}

This PR was automatically generated by VectorWave Healer based on execution logs.
Please review the changes before merging.
            """

            pr = self.repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=new_branch_name,
                base=base_branch
            )

            return f"✅ PR Created Successfully: {pr.html_url}"

        except Exception as e:
            logger.error(f"Failed to create PR: {e}")
            return f"❌ PR Creation Failed: {e}"